apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-q6lr
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0027-tenant/tkrw-pr712-0075-0027-app/devfile-sample-q6lr@sha256:ceec9ff03da1d80efaecc3f5631e3b8d0437296305d4b4ecd2e4ac8619e89325
        name: my-nodejs
        resources: {}
status: {}
